easy_admin:
    site_name: 'Alexandre'
    entities:
        # List the entity class name you want to manage
        Service:
            class: App\Entity\service
            form:
                fields: ['label', '$descriptionService', '$imageName', 'category', 'publisher']
            list:
                flieds: ['label', 'category', 'imageName', 'publisher']
        Category:
            class: App\Entity\Category
        User:
            class: App\Entity\User
    user:
        display_name: true
    design:
        brand_color: '#000'
