vich_uploader:
    db_driver: orm

    mappings:
        # Nom du mapping
        Image_du_produit:
            uri_prefix: /assets/images/uploads/service
            # Dossier d'upload
            upload_destination: '%kernel.project_dir%/public/assets/images/uploads/service'
        Image_des_horaires:
            uri_prefix: /assets/images/uploads/horaire
            # Dossier d'upload
            upload_destination: '%kernel.project_dir%/public/assets/images/uploads/horaire'
