create:
  path: /create
  controller: App\Controller\CategoryController::new
  methods: ['GET', 'POST']
update:
  path: /update/{id}
  controller: App\Controller\CategoryController::edit
  requirements:
    slug: '[a-z0-9\-]+'
  methods: ['GET', 'POST']
delete:
  path: /suppression/jesuissur/delete/{id}
  controller: App\Controller\CategoryController::delete
  requirements:
    slug: '[a-z0-9\-]+'
  methods: ['GET', 'POST', 'DELETE']
