#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# ------------HOMEPAGE--------------#
app_homepage:
    path: /
    controller: App\Controller\HomeController::index
# ------------CONTACT--------------#
app_contact_liste:
    path: /contact/liste
    controller: App\Controller\UserController::index
    methods: ['GET']
app_contact_show:
    path: /contact/show/{slug}
    controller: App\Controller\UserController::show
    methods: ['GET']
# ------------SERVICE--------------#
app_services_route:
    resource: routes_perso/app_services.yaml
    prefix: /admin/services
    name_prefix: app_services_
app_services_liste:
    path: /services/liste
    controller: App\Controller\ServiceController::liste
    methods: ['GET']
app_services_show:
    path: /services/{slug}
    controller: App\Controller\ServiceController::show
    requirements:
        slug: '[a-z0-9\-]+'
    methods: ['GET']
# ------------CATEGORY--------------#
app_category_route:
    resource: routes_perso/app_category.yaml
    prefix: /admin/category
    name_prefix: app_category_
app_category_liste:
    path: /admin/category/liste
    controller: App\Controller\CategoryController::liste
    methods: ['GET']
# ------------LOGIN&LOGOUT&USER--------------#
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
app_login:
    path: /login
    controller: App\Controller\RegistrationController::login
app_logout:
    path: /logout
# ------------------ADMIN--------------------#
app_admin_user:
    resource: routes_perso/admin_user.yaml
    prefix: /admin/user
    name_prefix: admin_user_
